const ContentPrivacyPolicies = {
  en: {
    title: 'Privacy policy',
    description: [
      'Awaq ("we", "our" or "us") is committed to protecting your privacy. This Privacy Policy explains how Awaq collects, uses and discloses your personal information.',
      "This Privacy Policy applies to our website, www.somosawaq.org and its associated subdomains (collectively, our 'Service'). By accessing or using our Service, you indicate that you have read, understood and agree to our collection, storage, use and disclosure of your personal information as described in this Privacy Policy and our Terms of Service."
    ],
    sections: [
      {
        title: 'Definitions and Key Terms',
        content: [
          {
            item: 'To help explain things as clearly as possible in this Privacy Policy, whenever any of these terms are referred to, they are strictly defined as:',
            list: [
              'Cookie: A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics and remember information about you such as your language preference or login information.',
              `Company: When this policy mentions "Company", "we", "us" or "our", it refers to Awaq Estaciones Biológicas, C/Doctor Torres Feced 20, Casa19 – 28770, which is responsible for your information under this Privacy Policy`,
              "Platform: Awaq's website (www.somosawaq.org), web application or public-facing digital application.",
              'Country: where Awaq or its owners/founders are located, in this case it is Spain.',
              'Customer: refers to the company, organization or person that registers to use the Awaq Service to manage relationships with its consumers or service users.',
              'Device: any device connected to the Internet, such as a phone, tablet, computer or any other device that can be used to visit www.somosawaq.org and use the services.',
              'IP Address: Every device connected to the Internet is assigned a number known as an Internet Protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device connects to the Internet.',
              'Personnel: refers to Awaq´s employees or those under contract to perform a service on behalf of a party.',
              'Personal data: any information that directly, indirectly or in connection with other information, including a personal identification number, allows the identification of a natural person.',
              'Service: refers to the service provided by Awaq as described in the relative terms (if available) and on this platform.',
              'Third Parties: refers to advertisers, contest sponsors, marketing and promotional partners, and others who provide our content or whose products or services we believe may interest you.',
              'Website: The www.somosawaq.org site, which can be accessed through this URL: https://www.somosawaq.org/',
              'You: a person or entity that is registered with www.somosawaq.org to use the Services.'
            ]
          }
        ]
      },
      {
        title: 'What information do we collect?',
        content: [
          {
            item: 'We collect information from you, always with your authorization, when you visit our platform, register on our site, request information, subscribe to our newsletter, respond to a survey or fill out a form. Depending on the nature of our relationship with you, we will process data to a greater or lesser extent, these being necessary, appropriate and relevant in all cases, in accordance with the purpose pursued. As stated above, we may process the following data:',
            list: ['Name', 'Telephone numbers', 'Email']
          },
          {
            item: 'This does not exclude the possibility that we may need additional personal data, so this list is indicative and not exhaustive.'
          }
        ]
      },
      {
        title: 'Where and when is customer and end-user information collected?',
        content: [
          {
            item: 'Awaq will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.'
          }
        ]
      },
      {
        title: 'How do we use the information we collect?',
        content: [
          {
            item: 'Any of the information we collect from you may be used in one of the following ways:',
            list: [
              'To personalize your experience (your information helps us better respond to your individual needs).',
              'To improve our platform (we continually strive to improve what our platform offers based on the information and feedback we receive from you).',
              'To improve customer service (your information helps us respond more effectively to your customer service requests and support needs).',
              'To send periodic emails whenever you choose to do so.'
            ]
          }
        ]
      },
      {
        title: 'How do we use your email address?',
        content: [
          {
            item: 'By submitting your email address on this platform, you agree to receive emails from us. You may opt out of any of these email lists at any time by clicking on the opt-out link or other unsubscribe option included in the respective email. We only send emails to people who have authorized us to contact them directly. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display personalized advertising to those who have opted in to receive communications from us.'
          },
          {
            item: 'Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.'
          }
        ]
      },
      {
        title: 'How long do we keep your information?',
        content: [
          {
            item: 'We will retain your personal information for as long as necessary or permitted in view of the purposes for which it was obtained. This is also the case for anyone with whom we share your information and who performs services on our behalf. When we no longer need to use your information and it is no longer necessary for us to retain it to comply with our legal or regulatory obligations, we will delete it from our systems or depersonalize it so that we cannot identify you.'
          }
        ]
      },
      {
        title: 'How do we protect your information?',
        content: [
          {
            item: 'We implement a variety of security measures to maintain the security of your personal information when you enter, submit or access your personal information. However, we cannot guarantee the absolute security of any information you transmit to Awaq or guarantee that your information on the Service will not be accessed, disclosed, altered or destroyed by a breach of any of our physical, technical or managerial safeguards.'
          }
        ]
      },
      {
        title: 'What are your rights?',
        content: [
          {
            item: 'You can exercise your rights of access, rectification, deletion and portability, limitation and/or opposition to processing, through the postal and electronic addresses indicated. This means that you have the right to:',
            list: [
              'To know if we are processing your data or not.',
              'To access your personal data.',
              'To request rectification of your data if it is inaccurate.',
              'To request the deletion of your data if you withdraw the consent granted.',
              'To send you the data we store about you in Awaq in a structured, commonly used or machine-readable format.',
              'To revoke consent for any treatment to which you have consented, at any time.'
            ]
          },
          {
            item: 'Likewise, if you consider that the processing of your personal data violates the regulations or your privacy rights, you can file a claim:',
            list: [
              'For more information about the guarantees to your privacy, you can contact Awaq through info@somosawaq.org',
              'Before the Spanish Data Protection Agency, through its electronic headquarters, or its postal address.'
            ]
          }
        ]
      },
      {
        title: 'When does Awaq transfer customer information to third parties?',
        content: [
          {
            item: 'We will never sell, rent or transfer your personal data, but it may be provided to the recipients indicated below, for the reasons explained below:',
            list: [
              'Public Administrations: for compliance with the legal obligations to which Awaq is subject due to its activity.',
              'Suppliers and other Non-Governmental Organizations that need to access their data for the provision of services that Awaq has contracted from said suppliers, and with which Awaq has signed the confidentiality and personal data processing contracts necessary and required by the regulations to protect your privacy.'
            ]
          },
          {
            item: 'If Awaq makes other transfers of personal data in the future, it will inform you in a timely manner and, if necessary, it will request your consent.'
          }
        ]
      },
      {
        title: 'Could my information be transferred to other countries?',
        content: [
          {
            item: 'Awaq is incorporated in Spain. Information collected through our website, through direct interactions with you, or through the use of our support services may be transferred from time to time to our offices or staff, or to third parties, located around the world, and may be viewed and be hosted anywhere in the world, including countries that may not have generally applicable laws regulating the use and transfer of such data. To the fullest extent permitted by applicable law, by using any of the above, you voluntarily consent to the cross-border transfer and hosting of such information.'
          }
        ]
      },
      {
        title: 'Is the information collected through the Awaq Service secure?',
        content: [
          {
            item: 'We take precautions to protect your information. We have physical, electronic and administrative procedures in place to help safeguard, prevent unauthorized access, maintain data security and correctly use your information. However, neither people nor security systems are infallible. Therefore, although we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any unwaivable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.'
          }
        ]
      },
      {
        title: 'Can I update or correct my information?',
        content: [
          {
            item: 'The rights you have to request updates or corrections to the information Awaq collects depend on your relationship with Awaq. Staff may update or correct their information as detailed in our internal company employment policies.'
          },
          {
            item: 'Customers have the right to request restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us to:',
            list: [
              '1. update or correct your personally identifiable information.',
              '2. change your preferences regarding communications and other information you receive from us, or.',
              '3. delete personally identifiable information maintained about you in our system (subject to the following paragraph), canceling your account.'
            ]
          },
          {
            item: 'Such updates, corrections, changes and deletions will have no effect on other information we maintain or information we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requiring a unique password) to verify your identity. You are responsible for maintaining the secrecy of your unique password and account information at all times'
          },
          {
            item: 'You should be aware that it is not technologically possible to delete each and every record of the information you have provided us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a form that cannot be erased and will be difficult or impossible for us to locate. Immediately upon receipt of your request, all personal information stored in the databases we actively use and other easily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically feasible. possible.'
          }
        ]
      },
      {
        title: 'Staff',
        content: [
          {
            item: 'If you are an Awaq employee or applicant, we collect information that you voluntarily provide to us. We use the information collected for human resources purposes to administer employee benefits and screen applicants.'
          },
          {
            item: 'You can contact us to:',
            list: [
              'update or correct your information',
              'change your preferences regarding communications and other information you receive from us, or',
              'receive a record of the information we have relating to you'
            ]
          },
          {
            item: 'Such updates, corrections, changes and deletions will have no effect on other information we maintain or information we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.'
          }
        ]
      },
      {
        title: 'Governing Law',
        content: [
          {
            item: 'This Privacy Policy is governed by the laws of Spain without regard to its conflict of laws provisions. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy, except for those who may have the right to bring claims under the Privacy Shield or the Swiss-American framework.'
          },
          {
            item: 'The laws of Spain, excluding its conflicts of laws, will govern this Agreement and your use of the Platform. Your use of the Platform may also be subject to other local, state, national or international laws.'
          },
          {
            item: 'By using www.somosawaq.org or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not interact with our website or use our services. Your continued use of the Website, direct interaction with us, or following the posting of changes to this Privacy Policy that do not materially affect the use or disclosure of your personal information will mean that you accept those changes.'
          }
        ]
      },
      {
        title: 'Your consent',
        content: [
          {
            item: 'We have updated our Privacy Policy to give you full transparency about what is set when you visit our site and how it is used. By using our platform, registering an account, you hereby accept our Privacy Policy and agree to its terms.'
          }
        ]
      },
      {
        title: 'Links to other Websites',
        content: [
          {
            item: "This Privacy Policy applies only to the Services. The Services may contain links to other websites that are not operated or controlled by Awaq. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those linked to on our platform, is subject to that website's own rules and policies. These third parties may use their own cookies or other methods to collect information about you."
          }
        ]
      },
      {
        title: "Children's Privacy",
        content: [
          {
            item: 'We do not target anyone under 13 years of age. We do not collect personally identifiable information from anyone under 13 years of age. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we take measures to delete that information from our servers.'
          }
        ]
      },
      {
        title: 'Changes to our Privacy Policy',
        content: [
          {
            item: 'We may change our Service and our policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and our policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you the opportunity to review them before they become effective. Then, if you continue to use the Service, you will be subject to the updated Privacy Policy. If you do not wish to accept this or any updated Privacy Policy, you may delete your account.'
          }
        ]
      },
      {
        title: 'Thirdparty services',
        content: [
          {
            item: `We may display, include or make available third party content (including data, information, applications and other product services) or provide links to third party websites or services ("Third Party Services").`
          },
          {
            item: 'You acknowledge and agree that Awaq shall not be responsible or liable for any Third Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Awaq does not assume and shall not have any obligation or liability to you or any other person or entity for any Third Party Services.'
          },
          {
            item: 'Third Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to the terms and conditions of such third parties.'
          }
        ]
      },
      {
        title: 'Tracking Technologies',
        content: [
          {
            list: ['Local Storage']
          },
          {
            item: 'Local storage, sometimes known as DOM storage, provides web applications with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies, but with greatly improved capacity and without information stored in the HTTP request header.'
          }
        ]
      },
      {
        title:
          'Information about the General Data Protection Regulation (GDPR)',
        content: [
          {
            item: 'We may collect and use information about you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we will explain exactly how and why this data is collected, and how we keep it protected against replication or incorrect use.'
          }
        ]
      },
      {
        title: 'What is GDPR?',
        content: [
          {
            item: 'GDPR is an EU-wide data protection and privacy law that regulates how companies protect the data of EU residents and improves the control that EU residents have over their personal data. The GDPR protects the data of its citizens and residents, even if it is transferred outside the EU area, which means that the GDPR applies to all EU and non-EU organizations that process personal information of European citizens.'
          }
        ]
      },
      {
        title: 'What is Personal Data?',
        content: [
          {
            item: "Any data that relates to an identifiable or identified individual. The GDPR covers a broad spectrum of information that could be used alone or in combination with other pieces of information to identify an individual. Personal data goes beyond a person's name or email address. Some examples include financial information, genetic data, biometric data, IP address, physical address, sexual orientation and ethnicity."
          },
          {
            item: 'Data protection principles include requirements such as:',
            list: [
              'Personal data collected must be processed fairly, lawfully and transparently and must only be used in a way that a person would reasonably expect.',
              'Personal data should only be collected to fulfill a specific purpose and should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.',
              'Personal data should not be kept longer than necessary to fulfill its purpose.',
              'Individuals covered by the GDPR have the right to access their own personal data. They can also request a copy of their data and that their data be updated, deleted, restricted or moved to another organization.'
            ]
          }
        ]
      },
      {
        title: 'Why is the GDPR important?',
        content: [
          {
            item: 'GDPR adds some new requirements regarding how companies must protect the personal data of individuals they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing higher fines for non-compliance.'
          }
        ]
      },
      {
        title:
          'Individual rights of the interested party: access, portability and deletion of data',
        content: [
          {
            item: 'We are committed to helping our clients meet the GDPR requirements regarding data subject rights. We store your personal data (name, telephone number, email address) and allow you to access, update, retrieve and delete it. We always give you access to your data and that of your clients.'
          }
        ]
      },
      {
        title: 'Changes to the Privacy Policy',
        content: [
          {
            item: 'Awaq reserves the right to modify this Privacy Policy to adapt it to legislative or jurisprudential developments, as well as industry practices.'
          },
          {
            item: 'These policies will be in force until they are modified by others duly published.'
          }
        ]
      },
      {
        title: 'Contact Us',
        content: [
          { item: 'Please feel free to contact us if you have any questions.' },
          { item: 'Via email: info@somosawaq.org' }
        ]
      }
    ]
  },
  es: {
    title: 'Política de privacidad',
    description: [
      'Awaq ("nosotros", "nuestro" o "nos") se compromete a proteger su privacidad. Esta Política de privacidad explica cómo Awaq recopila, usa y divulga su información personal.',
      `Esta Política de privacidad se aplica a nuestro sitio web, www.somosawaq.org y sus subdominios asociados (colectivamente, nuestro "Servicio"). Al acceder o utilizar nuestro Servicio, usted indica que ha leído, comprendido y aceptado nuestra recopilación, almacenamiento, uso y divulgación de su información personal como se describe en esta Política de privacidad y en nuestros Términos de servicio.`
    ],
    sections: [
      {
        title: 'Definiciones y Términos clave',
        content: [
          {
            item: 'Para ayudar a explicar las cosas de la manera más clara posible en esta Política de privacidad, cada vez que se hace referencia a cualquiera de estos términos, se definen estrictamente como:',
            list: [
              'Cookie: pequeña cantidad de datos generados por un sitio web y guardados por su navegador web. Se utiliza para identificar su navegador, proporcionar análisis, recordar información sobre usted, como su preferencia de idioma o información de inicio de sesión.',
              `Compañía: cuando esta política menciona "Compañía", "nosotros", "nos" o "nuestro", se refiere a Awaq Estaciones Biológicas, C/Doctor Torres Feced 20, Casa19 - 28770 que es responsable de su información en virtud de esta Política de privacidad.`,
              'Plataforma: el sitio web de Awaq en Internet (www.somosawaq.org), aplicación web o aplicación digital de cara al público.',
              'País: donde se encuentra Awaq o sus propietarios / fundadores, en este caso es España.',
              'Cliente: se refiere a la empresa, organización o persona que se registra para utilizar el Servicio de Awaq para gestionar las relaciones con sus consumidores o usuarios del servicio.',
              'Dispositivo: cualquier dispositivo conectado a Internet, como un teléfono, tablet, computadora o cualquier otro dispositivo que se pueda usar para visitar www.somosawaq.org y usar los servicios.',
              'Dirección IP: a cada dispositivo conectado a Internet se le asigna un número conocido como dirección de protocolo de Internet (IP). Estos números generalmente se asignan en bloques geográficos. A menudo, se puede utilizar una dirección IP para identificar la ubicación desde la que un dispositivo se conecta a Internet.',
              'Personal: se refiere a aquellas personas que son empleadas por Awaq o están bajo contrato para realizar un servicio en nombre de una de las partes.',
              'Datos personales: cualquier información que directa, indirectamente o en conexión con otra información, incluido un número de identificación personal, permita la identificación de una persona física.',
              'Servicio: se refiere al servicio brindado por Awaq como se describe en los términos relativos (si están disponibles) y en esta plataforma.',
              'Terceros: se refiere a anunciantes, patrocinadores de concursos, socios promocionales y de marketing, y otros que brindan nuestro contenido o cuyos productos o servicios que creemos que pueden interesarle.',
              'Sitio web: el sitio de www.somosawaq.org, al que se puede acceder a través de esta URL: https://www.somosawaq.org/',
              'Usted: una persona o entidad que está registrada con www.somosawaq.org para utilizar los Servicios.'
            ]
          }
        ]
      },
      {
        title: '¿Qué información recopilamos?',
        content: [
          {
            item: 'Recopilamos información suya, siempre con su autorización, cuando visita nuestra plataforma, se registra en nuestro sitio, solicita información, se suscribe a nuestro boletín, responde a una encuesta o completa un formulario. Dependiendo de la naturaleza de nuestra relación contigo, trataremos datos en mayor o menor medida, siendo estos necesarios, adecuados y pertinentes en todo caso, de acuerdo con la finalidad perseguida. Según lo expuesto anteriormente, podremos tratar los siguientes datos:',
            list: ['Nombre', 'Números de teléfono', 'Correo electrónico']
          }
        ]
      },
      {
        title:
          '¿Dónde y cuándo se recopila la información de los clientes y usuarios finales?',
        content: [
          {
            item: 'Awaq recopilará la información personal que nos envíe. También podemos recibir información personal sobre usted de terceros como se describe anteriormente.'
          }
        ]
      },
      {
        title: '¿Cómo usamos la información que recopilamos?',
        content: [
          {
            item: 'Cualquiera de la información que recopilamos de usted puede usarse de una de las siguientes maneras:',
            list: [
              'Para personalizar su experiencia (su información nos ayuda a responder mejor a sus necesidades individuales).',
              'Para mejorar nuestra plataforma (nos esforzamos continuamente por mejorar lo que ofrece nuestra plataforma en función de la información y los comentarios que recibimos de usted).',
              'Para mejorar el servicio al cliente (su información nos ayuda a responder de manera más efectiva a sus solicitudes de servicio al cliente y necesidades de soporte).',
              'Para enviar correos electrónicos periódicos siempre que así lo marque en su elección.'
            ]
          }
        ]
      },
      {
        title: '¿Cómo utilizamos su dirección de correo electrónico?',
        content: [
          {
            item: 'Al enviar su dirección de correo electrónico en esta plataforma, acepta recibir nuestros correos electrónicos. Puede cancelar su participación en cualquiera de estas listas de correo electrónico en cualquier momento haciendo clic en el enlace de exclusión voluntaria u otra opción para cancelar la suscripción que se incluye en el correo electrónico respectivo. Solo enviamos correos electrónicos a personas que nos han autorizado a contactarlos directamente. Al enviar su dirección de correo electrónico, también acepta permitirnos usar su dirección de correo electrónico para la orientación de la audiencia del cliente en sitios como Facebook, donde mostramos publicidad personalizada a personas específicas que han optado por recibir nuestras comunicaciones.'
          },
          {
            item: 'Nota: Si en algún momento desea cancelar la suscripción para no recibir correos electrónicos futuros, incluimos instrucciones detalladas para cancelar la suscripción en la parte inferior de cada correo electrónico.'
          }
        ]
      },
      {
        title: '¿Cuánto tiempo conservamos su información?',
        content: [
          {
            item: 'Conservaremos tu información personal el tiempo necesario o permitido en atención a los fines para los cuales se haya obtenido. Este también es el caso de cualquier persona con la que compartamos su información y que lleve a cabo servicios en nuestro nombre. Cuando ya no necesitemos usar su información y no sea necesario que la conservemos para cumplir con nuestras obligaciones legales o reglamentarias, la eliminaremos de nuestros sistemas o la despersonalizaremos para que no podamos identificarlo.'
          }
        ]
      },
      {
        title: '¿Cómo protegemos su información?',
        content: [
          {
            item: 'Implementamos una variedad de medidas de seguridad para mantener la seguridad de su información personal cuando ingresa, envía o accede a su información personal. Sin embargo, no podemos garantizar la seguridad absoluta de la información que transmita a Awaq ni garantizar que su información en el servicio no sea accedida, divulgada, alterada o destruida por una infracción de cualquiera de nuestras condiciones físicas, salvaguardias técnicas o de gestión.'
          }
        ]
      },
      {
        title: '¿Cuáles son tus derechos?',
        content: [
          {
            item: 'Puedes ejercitar tus derechos de acceso, rectificación, supresión y portabilidad, limitación y/u oposición al tratamiento, a través de las direcciones postal y electrónicas indicadas. Esto significa que tienes derecho a:',
            list: [
              'A saber si estamos tratando tus datos o no.',
              'A acceder a tus datos personales.',
              'A solicitar la rectificación de tus datos si son inexactos.',
              'A solicitar la supresión de tus datos si nos retiras el consentimiento otorgado.',
              'A remitirte los datos que guardamos sobre ti en Awaq en un formato estructurado, de uso común o lectura mecánica.',
              'A revocar el consentimiento para cualquier tratamiento para el que hayas consentido, en cualquier momento.'
            ]
          },
          {
            item: 'Asimismo, si consideras que el tratamiento de tus datos personales vulnera la normativa o tus derechos de privacidad, puedes presentar una reclamación:',
            list: [
              'Para más información sobre las garantías a tu privacidad, puedes dirigirte a Awaq a través de info@somosawaq.org',
              'Ante la Agencia Española de Protección de Datos, a través de su sede electrónica, o de su dirección postal.'
            ]
          }
        ]
      },
      {
        title: '¿Cuándo cede Awaq la información del cliente a terceros?',
        content: [
          {
            item: 'Nunca venderemos, alquilaremos o cederemos tus datos personales, pero estos podrán ser facilitados a los destinatarios que se indican a continuación, por los motivos que a continuación se explican:',
            list: [
              'Administraciones Públicas: para el cumplimiento de las obligaciones legales a las que Awaq está sujeta por su actividad.',
              'Proveedores y otras Organizaciones no Gubernamentales que precisen acceder a tus datos para la prestación de servicios que Awaq haya contratado a dichos proveedores, y con los cuales Awaq tiene suscritos los contratos de confidencialidad y de tratamiento de datos personales necesarios y exigidos por la normativa para proteger su privacidad.'
            ]
          },
          {
            item: 'Si en el futuro Awaq realizara otras cesiones de datos personales, te informará oportunamente y en caso de que resulte necesario solicitará tu consentimiento.'
          }
        ]
      },
      {
        title: '¿Podría transferirse mi información a otros países?',
        content: [
          {
            item: 'Awaq está incorporada en España. La información recopilada a través de nuestro sitio web, a través de interacciones directas con usted o del uso de nuestros servicios de ayuda puede transferirse de vez en cuando a nuestras oficinas o personal, o a terceros, ubicados en todo el mundo, y puede verse y alojarse en cualquier lugar del mundo, incluidos los países que pueden no tener leyes de aplicación general que regulen el uso y la transferencia de dichos datos. En la mayor medida permitida por la ley aplicable, al utilizar cualquiera de los anteriores, usted acepta voluntariamente la transferencia transfronteriza y el alojamiento de dicha información.'
          }
        ]
      },
      {
        title:
          '¿La información recopilada a través del Servicio de Awaq es segura?',
        content: [
          {
            item: 'Tomamos precauciones para proteger la seguridad de su información. Contamos con procedimientos físicos, electrónicos y administrativos para ayudar a salvaguardar, prevenir el acceso no autorizado, mantener la seguridad de los datos y usar correctamente su información. Sin embargo, ni las personas ni los sistemas de seguridad son infalibles. Por lo tanto, aunque hacemos todos los esfuerzos razonables para proteger su información personal, no podemos garantizar su seguridad absoluta. Si la ley aplicable impone algún deber irrenunciable de proteger su información personal, usted acepta que la mala conducta intencional serán los estándares utilizados para medir nuestro cumplimiento con ese deber.'
          }
        ]
      },
      {
        title: '¿Puedo actualizar o corregir mi información?',
        content: [
          {
            item: 'Los derechos que tienes para solicitar actualizaciones o correcciones de la información que recopila Awaq dependen de tu relación con Awaq. El personal puede actualizar o corregir su información según se detalla en nuestras políticas de empleo internas de la empresa.'
          },
          {
            item: 'Los clientes tienen derecho a solicitar la restricción de ciertos usos y divulgaciones de información de identificación personal de la siguiente manera. Puede comunicarse con nosotros para:',
            list: [
              'actualizar o corregir su información de identificación personal,',
              'cambiar sus preferencias con respecto a las comunicaciones y otra información que recibe de nosotros, o',
              'eliminar la información de identificación personal que se mantiene sobre usted en nuestro sistema (sujeto al siguiente párrafo), cancelando su cuenta.'
            ]
          },
          {
            item: 'Dichas actualizaciones, correcciones, cambios y eliminaciones no tendrán ningún efecto sobre otra información que mantenemos o información que hayamos proporcionado a terceros de acuerdo con esta Política de privacidad antes de dicha actualización, corrección, cambio o eliminación. Para proteger su privacidad y seguridad, podemos tomar medidas razonables (como solicitar una contraseña única) para verificar su identidad. Usted es responsable de mantener en secreto su contraseña única y la información de su cuenta en todo momento.'
          },
          {
            item: 'Debe tener en cuenta que tecnológicamente no es posible eliminar todos y cada uno de los registros de la información que nos ha proporcionado de nuestro sistema. La necesidad de realizar copias de seguridad de nuestros sistemas para proteger la información de pérdidas involuntarias significa que puede existir una copia de su información en una forma que no se pueda borrar y que será difícil o imposible de localizar para nosotros. Inmediatamente después de recibir su solicitud, toda la información personal almacenada en las bases de datos que usamos activamente y otros medios fácilmente buscables se actualizará, corregirá, cambiará o eliminará, según corresponda, tan pronto como y en la medida en que sea razonable y técnicamente posible.'
          }
        ]
      },
      {
        title: 'Personal',
        content: [
          {
            item: 'Si es un trabajador o solicitante de Awaq, recopilamos la información que nos proporciona voluntariamente. Usamos la información recopilada con fines de recursos humanos para administrar los beneficios a los trabajadores y seleccionar a los solicitantes.'
          },
          {
            item: 'Puede comunicarse con nosotros para:',
            list: [
              'actualizar o corregir su información,',
              'cambiar sus preferencias con respecto a las comunicaciones y otra información que reciba de nosotros, o',
              'recibir un registro de la información que tenemos relacionada con usted.'
            ]
          },
          {
            item: 'Dichas actualizaciones, correcciones, cambios y eliminaciones no tendrán ningún efecto sobre otra información que mantenemos o información que hayamos proporcionado a terceros de acuerdo con esta Política de privacidad antes de dicha actualización, corrección, cambio o eliminación.'
          }
        ]
      },
      {
        title: 'Ley que Rige',
        content: [
          {
            item: 'Esta Política de privacidad se rige por las leyes de España sin tener en cuenta su disposición sobre conflicto de leyes. Usted acepta la jurisdicción exclusiva de los tribunales en relación con cualquier acción o disputa que surja entre las partes en virtud de esta Política de privacidad o en relación con ella, excepto aquellas personas que puedan tener derecho a presentar reclamaciones en virtud del Escudo de privacidad o el marco suizo-estadounidense.'
          },
          {
            item: 'Las leyes de España, excluyendo sus conflictos de leyes, regirán este Acuerdo y su uso de la plataforma. Su uso de la plataforma también puede estar sujeto a otras leyes locales, estatales, nacionales o internacionales.'
          },
          {
            item: 'Al usar www.somosawaq.org o comunicarse con nosotros directamente, significa que acepta esta Política de privacidad. Si no está de acuerdo con esta Política de privacidad, no debe interactuar con nuestro sitio web ni utilizar nuestros servicios. El uso continuo del sitio Web, la interacción directa con nosotros o después de la publicación de cambios en esta Política de privacidad que no afecten significativamente el uso o divulgación de su información personal significará que acepta esos cambios.'
          }
        ]
      },
      {
        title: 'Tu consentimiento',
        content: [
          {
            item: 'Hemos actualizado nuestra Política de privacidad para brindarle total transparencia sobre lo que se establece cuando visita nuestro sitio y cómo se utiliza. Al utilizar nuestra plataforma, registrar una cuenta, por la presente acepta nuestra Política de privacidad y acepta sus términos.'
          }
        ]
      },
      {
        title: 'Enlaces a otros Sitios Web',
        content: [
          {
            item: 'Esta Política de privacidad se aplica solo a los Servicios. Los Servicios pueden contener enlaces a otros sitios web que Awaq no opera ni controla. No somos responsables por el contenido, la precisión o las opiniones expresadas en dichos sitios web, y dichos sitios web no son investigados, monitoreados o verificados por nuestra precisión o integridad. Recuerde que cuando utiliza un enlace para ir desde los Servicios a otro sitio web, nuestra Política de privacidad deja de estar en vigor. Su navegación e interacción en cualquier otro sitio web, incluidos aquellos que tienen un enlace en nuestra plataforma, están sujetos a las propias reglas y políticas de ese sitio web. Dichos terceros pueden utilizar sus propias cookies u otros métodos para recopilar información sobre usted.'
          }
        ]
      },
      {
        title: 'Privacidad de los Niños',
        content: [
          {
            item: 'No nos dirigimos a ninguna persona menor de 13 años. No recopilamos información de identificación personal de ninguna persona menor de 13 años. Si usted es padre o tutor y sabe que su hijo nos ha proporcionado Datos Personales, comuníquese con nosotros. Si nos damos cuenta de que hemos recopilado datos personales de cualquier persona menor de 13 años sin la verificación del consentimiento de los padres, tomamos medidas para eliminar esa información de nuestros servidores.'
          }
        ]
      },
      {
        title: 'Cambios en nuestra Política de Privacidad',
        content: [
          {
            item: 'Podemos cambiar nuestro Servicio y nuestras políticas, y es posible que debamos realizar cambios en esta Política de privacidad para que reflejen con precisión nuestro Servicio y nuestras políticas. A menos que la ley exija lo contrario, le notificaremos (por ejemplo, a través de nuestro Servicio) antes de realizar cambios en esta Política de privacidad y le daremos la oportunidad de revisarlos antes de que entren en vigencia. Luego, si continúa utilizando el Servicio, estará sujeto a la Política de privacidad actualizada. Si no desea aceptar esta o cualquier Política de privacidad actualizada, puede eliminar su cuenta.'
          }
        ]
      },
      {
        title: 'Servicios de terceros',
        content: [
          {
            item: `Podemos mostrar, incluir o poner a disposición contenido de terceros (incluidos datos, información, aplicaciones y otros servicios de productos) o proporcionar enlaces a sitios web o servicios de terceros ("Servicios de terceros").`
          },
          {
            item: 'Usted reconoce y acepta que Awaq no será responsable de ningún Servicio de terceros, incluida su precisión, integridad, puntualidad, validez, cumplimiento de los derechos de autor, legalidad, decencia, calidad o cualquier otro aspecto de los mismos. Awaq no asume ni tendrá ninguna obligación o responsabilidad ante usted o cualquier otra persona o entidad por los Servicios de terceros.'
          },
          {
            item: 'Los Servicios de terceros y los enlaces a los mismos se brindan únicamente para su conveniencia y usted accede a ellos y los usa completamente bajo su propio riesgo y sujeto a los términos y condiciones de dichos terceros.'
          }
        ]
      },
      {
        title: 'Tecnologías de Seguimiento',
        content: [
          {
            list: ['Almacenamiento Local']
          },
          {
            item: 'El almacenamiento local, a veces conocido como almacenamiento DOM, proporciona a las aplicaciones web métodos y protocolos para almacenar datos del lado del cliente. El almacenamiento web admite el almacenamiento de datos persistente, similar a las cookies, pero con una capacidad muy mejorada y sin información almacenada en el encabezado de solicitud HTTP.'
          }
        ]
      },
      {
        title:
          'Información sobre el Reglamento general de protección de datos (RGPD)',
        content: [
          {
            item: 'Es posible que recopilemos y utilicemos información suya si pertenece al Espacio Económico Europeo (EEE), y en esta sección de nuestra Política de privacidad vamos a explicar exactamente cómo y por qué se recopilan estos datos, y cómo los mantenemos bajo protección contra la replicación o el uso incorrecto.'
          }
        ]
      },
      {
        title: '¿Qué es RGPD?',
        content: [
          {
            item: 'RGPD es una ley de privacidad y protección de datos en toda la UE que regula cómo las empresas protegen los datos de los residentes de la UE y mejora el control que los residentes de la UE tienen sobre sus datos personales. El GDPR protege los datos de sus ciudadanos y residentes, incluso si se transfieren fuera de la zona de la UE, lo que significa que el GDPR se aplica a todas las organizaciones de la UE y de fuera de la UE, que procesan la información personal de los ciudadanos europeos.'
          }
        ]
      },
      {
        title: '¿Qué son los Datos Personales?',
        content: [
          {
            item: 'Cualquier dato que se relacione con un individuo identificable o identificado. El RGPD cubre un amplio espectro de información que podría usarse por sí sola o en combinación con otras piezas de información para identificar a una persona. Los datos personales van más allá del nombre o la dirección de correo electrónico de una persona. Algunos ejemplos incluyen información financiera, opiniones políticas, datos genéticos, datos biométricos, direcciones IP, dirección física, orientación sexual y origen étnico.'
          },
          {
            item: 'Los principios de protección de datos incluyen requisitos tales como:',
            list: [
              'Los datos personales recopilados deben procesarse de manera justa, legal y transparente y solo deben usarse de la manera que una persona esperaría razonablemente.',
              'Los datos personales solo deben recopilarse para cumplir con un propósito específico y solo deben usarse para ese propósito. Las organizaciones deben especificar por qué necesitan los datos personales cuando los recopilan.',
              'Los datos personales no deben conservarse más tiempo del necesario para cumplir con su propósito.',
              'Las personas cubiertas por el RGPD tienen derecho a acceder a sus propios datos personales. También pueden solicitar una copia de sus datos y que sus datos se actualicen, eliminen, restrinjan o muevan a otra organización.'
            ]
          }
        ]
      },
      {
        title: '¿Por qué es importante el RGPD?',
        content: [
          {
            item: 'RGPD agrega algunos requisitos nuevos con respecto a cómo las empresas deben proteger los datos personales de las personas que recopilan y procesan. También aumenta las apuestas para el cumplimiento al aumentar la aplicación e imponer mayores multas por incumplimiento.'
          }
        ]
      },
      {
        title:
          'Derechos individuales del interesado: acceso, portabilidad y eliminación de datos',
        content: [
          {
            item: 'Nos comprometemos a ayudar a nuestros clientes a cumplir los requisitos del GDPR en materia de derechos de los interesados. Almacenamos sus datos personales (nombre, número de teléfono, dirección de correo electrónico) y le permitimos acceder a ellos, actualizarlos, recuperarlos y eliminarlos. Siempre le damos acceso a sus datos y a los de sus clientes.'
          }
        ]
      },
      {
        title: 'Cambios en la Política de Privacidad',
        content: [
          {
            item: 'Awaq se reserva el derecho a modificar la presente Política de Privacidad para adaptarla a novedades legislativas o jurisprudenciales, así como a prácticas de la industria.'
          },
          {
            item: 'Estas políticas estarán vigentes hasta que sean modificadas por otras debidamente publicadas.'
          }
        ]
      },
      {
        title: 'Contáctenos',
        content: [
          { item: 'No dude en contactarnos si tiene alguna pregunta.' },
          { item: 'A través de correo electrónico: info@somosawaq.org' }
        ]
      }
    ]
  }
}
export default ContentPrivacyPolicies
