name: Continous Integration

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  type-check:
    name: Check code with TypeScript linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript check
        run: npm run check

  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Formatter
        run: npm run check-format && echo "All is formatted!"
